
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:


- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'Pay-As-You-Go(e0b04bb4-2704-41a6-894f-a1032232638a)'
    appName: 'tataikhalimereppapatereuhtoddungabora'
    containers: 'build1:latest'